Students/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from Students import views

app_name = 'Students'

urlpatterns = [
    url(r'^index$', views.index, name='index'),
    url(r'^register$', views.register.as_view(), name='register'),
    # url(r'^login$', views.login, name='login'),
    url(r"login/$", auth_views.LoginView.as_view(template_name="Students/login.html"),name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r'^question/$', views.question, name='question'),
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<question_id>[0-9]+)/results/$',views.results, name='results'),
    url(r'^rules$', views.rules, name='rules')

]

quiz/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from quiz import views

app_name = 'quiz'

urlpatterns = [
    url(r'^question/$', views.question, name='question'),
    url(r'^question/(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^create/$', views.create_a_quiz_view, name='create_a_quiz_view')
]

quiz_app/urls.py
from django.conf.urls import url, include
from quiz_app import views
from django.contrib.auth import views as auth_views
from django.contrib import admin

app_name = 'Students'

urlpatterns = [
    url(r'^$', views.homepage, name= 'homepage'),
    url(r'^admin/', admin.site.urls),
    # url(r'^login/$', auth_views.login, name='login'),
    # url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^student/', include('Students.urls')),
    url(r'^quiz/', include('quiz.urls'))
]

Students/models.py
from django.contrib import auth
from django.db import models
from django.utils import timezone


# Create your models here.

class Student(models.Model):
    YEAR_CHOICES = (
        ('1', 'FIRST YEAR'),
        ('2', 'SECOND YEAR'),
        ('3', 'THIRD YEAR'),
        ('4', 'FOURTH YEAR'),
    )

    HOSTEL_NAME = (
        ('Y', 'YASHODHARA BHAVAN'),
        ('K', 'KALPANA BHAVAN'),
        ('V', 'VRINDAVAN BHAVAN'),
        ('S', 'SAKET BHAVAN'),
        ('P', 'PANCHAVATI BHAVAN'),
        ('J', 'JAYBHARAT BHAVAN'),
    )

    roll_no = models.IntegerField(primary_key=True)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email_id = models.EmailField(max_length=30, blank=True)
    mobile_number = models.IntegerField(unique=True)
    year = models.CharField(max_length=1, choices=YEAR_CHOICES)
    hostel_name = models.CharField(max_length=1, choices=HOSTEL_NAME)

    def __str__(self):
        return ("%s %s" % (self.first_name, self.last_name))


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    is_published = models.BooleanField('is published')
    pub_date = models.DateTimeField(default = False)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='choices')
    choice_text = models.CharField(max_length=200)
    is_correct = models.BooleanField(default=True)

    def __str__(self):
        return self.choice_text


# User authentication class
class User(auth.models.User, auth.models.PermissionsMixin):
    
    def __str__(self):
        return "@{}".format(self.username)

quiz/models.py
# Create your models here.

from django.db import models
from django.contrib import auth
from django.utils import timezone

class Answer(models.Model):
    """
    Answer's Model, which is used as the answer in Question Model
    """
    text = models.CharField(max_length=128, verbose_name=u'Answer\'s text')
    is_valid = models.BooleanField(default=False)

    def __str__(self):
        return self.text


class Question(models.Model):
    question_text = models.CharField(max_length=256, verbose_name=u'Question\'s text')
    answers = models.ManyToManyField(Answer)
    is_published = models.BooleanField(default=False)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return "{content} - {published}".format(content=self.question_text, published=self.is_published)

class Exam(models.Model):
    """
    Exam's model, works as a wrapper for the questions
    """
    name = models.CharField(max_length=64, verbose_name=u'Exam name', )
    slug = models.SlugField()
    questions = models.ManyToManyField(Question)

    def __str__(self):
        return self.name


#model for creating a quiz
# class Create_a_Quiz(models.Model):
#     author = models.ForeignKey('auth.User')
#     title = models.CharField(max_length = 200)
#     created_date = models.DateTimeField(default = timezone.now)
#     published_date = models.DateTimeField(blank = True, null = True)

#     def publish(self):
#         self.published_date = timezone.now()
#         self.save()

#     def __str__(self):
#         return self.title
    

Students/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Display name"
        self.fields["email"].label = "Email address"

quiz/forms.py
from django.core import validators
from django import forms

class Create_a_quiz_Form(forms.Form):
	topic = forms.CharField(required=True, max_length = 30)
	about_the_quiz = forms.CharField(widget=forms.Textarea)
	creator = forms.EmailField()

Students/views.py
from django.contrib.auth import login, logout
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView
from . import forms

from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

from Students.models import Question


def results(request, question_id):
    response = "You're looking at the result of question %s."
    return HttpResponse(response % question_id)


def index(request):
    '''context = {
        "questions": Question.objects.all()
    }'''

    return render(request, "Students/index.html")


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'quiz/question_detail.html', {'question': question})


class register(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("Students:login")
    template_name = "Students/registration.html"


    # # All code for registration here.
    # return render(request, "Students/registration.html")


# def login(request):


#   # Add code here for login 

#   return render(request, "Students/login.html")

def question(request):
    return render(request, 'Students/question.html') 

def rules(request):

    return render(request, 'Students/rules.html')

quiz/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone

# Create your views here.
from quiz.models import Question, Answer, Exam
from django.core.mail import send_mail
from . import forms

def question(request):
	question_list = Question.objects.order_by('-pub_date')[:5]
	return render(request, 'quiz/question.html', {'question_list': question_list})

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'quiz/detail.html', {'question': question})

def create_a_quiz_view(request):
	form = forms.Create_a_quiz_Form()
	return render(request, 'quiz/form.html', {'form': form})

quiz_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

def homepage(request):

	return render(request, "homepage.html")

templates/Students/base.html
<!DOCTYPE html>

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Rubik" rel="stylesheet">

    <title>Quiz App | Student</title>
  </head>
  <body class="bg-light">
    <nav class="navbar navbar-dark bg-dark">
      <div class="container">
        <!-- <h1><a href="{% url 'homepage' %}" class="navbar-brand">
        <img src="http://placehold.it/40x40" alt="Logo" class="rounded">
         Quiz App</a></h1> -->
         {% if user.is_authenticated %}
          <h1><img src="http://placehold.it/40x40" alt="Logo" class="rounded"></h1>
        {% else %}
          <h1><a href="{% url 'homepage' %}" class="navbar-brand">
          <img src="http://placehold.it/40x40" alt="Logo" class="rounded">
           Quiz App</a></h1>
        {% endif %}
        <form class="form-inline">
          <div class="mx-auto">
            {% if user.is_authenticated %}
            <button type="submit" class="btn btn-link btn-danger"><a href="{% url 'Students:logout' %}" class="text-white">Log Out <i class="fa fa-sign-out" aria-hidden="true"></i></a></button>

            {% endif %}
          </div>
        </form>
      </div>
    </nav>

    {% block body_block %}
    {% endblock %}
    <p><hr></p>
    <footer class="bg-light text-muted">
      <div class="container py-2">
        <ul class="list-inline mb-0 text-center">
          <li class="list-inline-item">&copy; 2018 Quiz App. </li>
          <li class="list-inline-item">All rights reserved.</li>
        </ul>
      </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/smooth-scroll/12.1.5/js/smooth-scroll.min.js" integrity="sha256-MMt0/21G3z0Zg4ET1kI3HC9npItDowkitRDVr0FhCxA=" crossorigin="anonymous"></script>
  </body>
</html>

templates/Students/index.html
<!DOCTYPE html>
{% extends "Students/base.html" %}
{% load bootstrap4 %}
	{% block body_block%}
	<div class="container">
		<h1 class="my-3 mb-sm-5 text-center">Select one</h1>
	    <div class="row">
			<div class="col-12 col-lg-6 col-md-6 my-4">
				 <div class="card card-outline-success text-center">
		            <div class="card-header bg-success text-white">
		              <h2>Create Quiz</h2>
		            </div>
		            <div class="card-block">
		              <h4 class="card-text text-left my-2 text-center">Create your own quiz and submit the quiz to our site.</h4>
		            </div>
		            <div class="card-footer">
		              <button type="button" class="btn btn-success btn-lg">Select</button>
		            </div>
          		</div>
			</div>
			<div class="col-12 col-lg-6 col-md-6 my-4">
				<div class="card card-outline-primary text-center">
		            <div class="card-header bg-primary text-white">
		              <h2>Start Quiz</h2>
		            </div>
		            <div class="card-block">
		              <h4 class="card-text text-left my-2 text-center">Start existing quizzes on various topics</h4>
		            </div>
		            <div class="card-footer">
		              <button type="button" class="btn btn-primary btn-lg"><a href="{% url 'Students:rules' %}" class="text-white">Select</a></button>
		            </div>
          		</div>
			</div>	
		</div>	
	</div>	
	{% endblock %}

templates/Students/login.html
<!DOCTYPE html>
{% extends "Students/base.html" %}
{% load bootstrap4 %}

	{% block body_block %}
    <div class="container">
	    <h1>Log In</h1>
	    <form method="POST">
	        {% csrf_token %}
	        {% bootstrap_form form %}
	        <input type="submit" value="Login" class="btn btn-default">
	    </form>
		</div>
  {% endblock %}

templates/Students/rules.html
<!DOCTYPE html>
{% extends "Students/base.html" %}
{% load bootstrap4 %}
	{% block body_block%}
	<div class="container">
	    <div class="row">
	        <!-- <div class="col-12 text-center my-4">
				<h2>Online Quiz</h2>
				<p>This time in QUIZ-APP, we bring to you an online quiz on topics related to various fields of science and technology.
				</p>
				<p style="color:green;">
				    <i><b>Online Quiz is over. You can download report of your attempts and answers to all questions.</b></i>
				</p>
				<p style="text-align:center;">
				    <a href="/quiz_app/your-attempts/">
				        <button>See your attempts</button>
				    </a>
				&nbsp;&nbsp;&nbsp;&nbsp;
				<a href="/quiz/see-answers/">
				    <button>See Answers</button>
				</a>
				</p>
			</div> -->
			<div class="card border-info mx-4 my-4">
			    <div class="card-body text-info">
			        <h4 class="card-title">Rules :</h4>
				    <p class="card-text">
						<ul style="list-style:decimal;">
						    <!-- <li>At max only 10 questions can be answered in one day.</li> -->
						    <li>Every question is having a timeout of at max 3 minutes. If it is answered after timeout, no marks will be awarded.
						    </li>
						    <li>For every question there is a minimum time limit (generally 8 seconds but may be more or less depending on word count of question). If time taken to answer is more than minimum time limit, then marks will be awarded using following formula :
						    <br>
						    <h4><span class="badge badge-danger"><i>marks_awarded = (maximum_marks * minimum_time_limit) / actual_time_taken</i></span></h4>
						    (** Rounded off upto two decimal points.)
						    </li>
						    <li>Try to answer as quickly as you can.</li>
						    <li>No question will be repeated for a user even if he refuses to answer after seeing it. Even if you skip aquestion, it will be counted as attempted question.
						    </li>
						    <li>Since, questions are selected randomly from a large database, <b>probability of two persons getting the same question simultaneously is less than 0.50 percent.</b> Please don't try to behave smartly.
						    </li>

						    <!-- <li>Check your score, rank etc. in the <a href="/quiz/dashboard/">dashboard</a>.</li> -->
						    <li>If difference between "Time Taken between Request and Submission to Server" and "Time Taken Calculated by Timer" is found more than 10 seconds, it means either your connection is very slow or you are trying to manipulate timer. If this will happen frequently, your quiz account will be disabled and no marks will be awarded for such submissions. It's advised to use high speed internet for this event.
						    </li>
						</ul>
				    </p>
				    <a href="#" class="btn btn-info">Start Quiz</a>
				</div>  
				<div class="card-footer">Created DD-MM-YYYY</div>  
			</div>	
		</div>	
	</div>	
	{% endblock %}

templates/homepage.html
<!DOCTYPE html>

{% extends "base.html" %}

  {% block body_block %}
    <section id="section-jumbotron" class="jumbotron jumbotron-fluid d-flex justify-content-center align-items-center">
      <div class="container text-center">
        <h1 class="display-1 text-primary">Quiz App</h1>
        <p class="display-4 d-none d-sm-block">Test your skills and become a master.</p>
        <p class="lead">We organize quizzes on various topics.</p>
        <p class="lead">Sign up if you haven't already and get access to millions of quizzes on the topic of your interest.</p>
        <p><strong> Start Your Journey Here:</strong></p>
        <a href="{% url 'Students:register' %}" class="btn btn-lg btn-primary mt-1"><i class="fa fa-user-plus" aria-hidden="true"></i> Sign Up</a>
        <a href="{% url 'Students:login' %}" class="btn btn-lg btn-primary mt-1"><i class="fa fa-sign-in" aria-hidden="true"></i> Log In</a>
      </div>  
    </section>
    <footer class="bg-light">
      <div class="container">
        <div class="row">
          <div class="col-12 col-sm-6 col-lg-3"> 
            <h6>Quick Links</h6>
            <ul class="list-unstyled">
              <li><a href="#">Home</a></li>
              <li><a href="#">What's new?</a></li>
              <li><a href="#">Support</a></li>
              <!-- <li><a href="#">My account</a></li> -->
              <!-- <li><a href="#">Cancel subscription</a></li> -->
            </ul>  
          </div>
          <div class="col-12 col-sm-6 col-lg-3"> 
            <h6>Information</h6>
            <ul class="list-unstyled">
              <li><a href="#">About us</a></li>
              <li><a href="#">Jobs</a></li>
              <!-- <li><a href="#">Press info</a></li> -->
              <li><a href="#">Contact</a></li>
              <li><a href="#">Partnership</a></li>
            </ul>  
          </div>
          <div class="col-12 col-sm-6 col-lg-3"> 
            <h6>Follow Us</h6>
            <ul class="list-unstyled">
              <li><a href="#"><i class="fa fa-fw fa-facebook " aria-hidden="true"></i> Facebook</a></li>
              <li><a href="#"><i class="fa fa-fw fa-instagram " aria-hidden="true"></i> Instagram</a></li>
              <li><a href="#"><i class="fa fa-fw fa-twitter " aria-hidden="true"></i> Twitter</a></li>
              <!-- <li><a href="#"><i class="fa fa-fw fa-youtube " aria-hidden="true"></i> YouTube</a></li> -->
              <!-- <li><a href="#"><i class="fa fa-fw fa-linkedin " aria-hidden="true"></i> LinkedIn</a></li> --> 
            </ul>        
          </div>
          <div class="col-12 col-sm-6 col-lg-3"> 
            <h6>Our location:</h6>
            <address>
              <!-- <strong>Quiz App</strong><br> -->
              BIET, Jhansi<br>
              Uttar Pradesh, 284128<br>
              <i class="fa fa-fw fa-phone" aria-hidden="true"></i> <span class="sr-only">Telephone:</span><a href="tel:+918787040049">(+91) 8787040049</a><br>
              <i class="fa fa-fw fa-phone" aria-hidden="true"></i> <span class="sr-only">Telephone:</span><a href="tel:+919721304421">(+91) 9721304421</a><br>
              <i class="fa fa-fw fa-inbox" aria-hidden="true"></i> <span class="sr-only">Mail:</span><a href="mailto:bietquiz@gmial.com">bietquiz@gmail.com</a>
            </address>
          </div>
        </div> 
        <div class="row">
          <div class="col-12 col-sm-6 col-lg-9">
              <ul class="list-inline">
                <li class="list-inline-item">&copy; 2018 Quiz App.</li>
                <li class="list-inline-item">All rights reserved.</li>
                <li class="list-inline-item"><a href="#" data-toggle="modal" data-target="#modal">Terms of use and privacy policy.</a></li>
              </ul>
          </div>
          <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="modalTitle">Terms and conditions</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas feugiat, urna ut pharetra ultricies, augue tellus euismod turpis, vitae semper ipsum augue a velit. Pellentesque id finibus velit. Ut sagittis maximus maximus. In aliquet enim sed turpis mollis ornare. Suspendisse elementum a magna eu luctus. Etiam tincidunt mattis mauris, non lobortis nulla tempor in. Sed lacinia metus viverra, scelerisque enim sed, sollicitudin magna. Sed non augue sit amet nisl tincidunt ultrices. Praesent nec lacus eget tortor ultricies pulvinar. Praesent euismod ut lorem sit amet bibendum.</p>

                  <p>Pellentesque vitae convallis magna. Morbi non elementum mi. Suspendisse at mollis arcu, eu tempus tellus. Aenean fringilla eleifend nisl. Aliquam erat volutpat. Sed a tortor quis tortor convallis mattis. Nunc congue massa vitae lectus dictum, a mattis metus dignissim.</p>

                  <p>Nulla feugiat, lorem sit amet vehicula hendrerit, velit eros pellentesque est, at dictum elit risus id diam. In ante lorem, blandit vel dui in, sagittis laoreet erat. Proin dictum sit amet urna ut placerat. Pellentesque laoreet, dolor vitae facilisis feugiat, quam quam gravida elit, nec sagittis orci metus at leo. In scelerisque felis vel neque lobortis ullamcorper. Praesent quis sagittis neque, nec eleifend neque. Suspendisse at consectetur eros. Mauris lectus libero, molestie vel dapibus sit amet, luctus gravida ante. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut libero neque, pretium quis malesuada eget, congue ac mauris.</p>

                  <p>Aenean quis tristique libero. Vestibulum sagittis, sapien gravida lobortis posuere, diam arcu auctor libero, at tempor mauris nulla vel odio. Phasellus semper eros rutrum mi scelerisque interdum. Maecenas euismod est sit amet justo vestibulum bibendum. Etiam scelerisque sodales nisi nec efficitur. Pellentesque arcu mauris, accumsan eget mollis at, ultrices id ante. Duis in mi eget nisi euismod gravida. Cras pharetra sollicitudin elit, vel eleifend felis dignissim non. Integer leo ex, feugiat eu lorem egestas, mollis suscipit nulla. Duis quis tellus nulla. Maecenas risus ipsum, fringilla at orci sit amet, mattis fringilla orci. Vivamus odio tellus, ornare eu leo id, pellentesque sodales ante.</p>

                  <p>Sed laoreet ut ligula eget fringilla. Suspendisse dapibus dui at ex dictum hendrerit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi efficitur ac purus eget dignissim. Aliquam ultrices, orci finibus sollicitudin tempus, elit metus scelerisque magna, a rhoncus justo nisl vitae lectus. Nam mollis sed est ut ullamcorper. Curabitur consequat feugiat erat quis molestie. Fusce suscipit sem et nulla dignissim, id malesuada felis laoreet. Cras leo ligula, vulputate id mi ac, gravida porta sem. Mauris ullamcorper lectus ac eleifend elementum. Ut id velit consequat, facilisis leo vitae, volutpat nisi. Nunc hendrerit libero mi. Integer scelerisque mattis neque placerat condimentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla eu odio mi. Duis interdum vulputate turpis pretium congue.</p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  {% endblock%}

templates/quiz/base.html
<!DOCTYPE html>

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Rubik" rel="stylesheet">

    <title>Quiz App | Student</title>
  </head>
  <body class="bg-light">
    <nav class="navbar navbar-dark bg-dark">
      <div class="container">
        <!-- <h1><a href="{% url 'homepage' %}" class="navbar-brand">
        <img src="http://placehold.it/40x40" alt="Logo" class="rounded">
         Quiz App</a></h1> -->
         {% if user.is_authenticated %}
          <h1><img src="http://placehold.it/40x40" alt="Logo" class="rounded"></h1>
        {% else %}
          <h1><a href="{% url 'homepage' %}" class="navbar-brand">
          <img src="http://placehold.it/40x40" alt="Logo" class="rounded">
           Quiz App</a></h1>
        {% endif %}
        <form class="form-inline">
          <div class="mx-auto">
            {% if user.is_authenticated %}
            <button type="submit" class="btn btn-link btn-danger"><a href="{% url 'Students:logout' %}" class="text-white">Logout</a></button>

            {% endif %}
          </div>
        </form>
      </div>
    </nav>

    {% block body_block %}
    {% endblock %}
    <p><hr></p>
    <footer class="bg-light text-muted">
      <div class="container py-2">
        <ul class="list-inline mb-0 text-center">
          <li class="list-inline-item">&copy; 2018 Quiz App. </li>
          <li class="list-inline-item">All rights reserved.</li>
        </ul>
      </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/smooth-scroll/12.1.5/js/smooth-scroll.min.js" integrity="sha256-MMt0/21G3z0Zg4ET1kI3HC9npItDowkitRDVr0FhCxA=" crossorigin="anonymous"></script>
  </body>
</html>

templates/quiz/detail.html
<!DOCTYPE html>
{% extends "Students/base.html" %}
{% load bootstrap4 %}

	{% block body_block %}
        <div class="container">
            {% if question %}
	            <ul>
			        <li>Question : <i>{{ question.question_text }}</i></li>
			        <!-- <li><a href="#">{{ question.answers }}</a></li> -->
			        <li> Question Published Date : <i>{{ question.pub_date }}</i></li>
			    </ul>
			{% else %}
			    <p>No questions are available.</p>
			{% endif %}
        	 
        </div>
    {% endblock %}